# Generated by Django 5.2.8 on 2025-11-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('publisher', 'Publisher'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('reader', 'Reader')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('declined_for', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('publisher', 'Publisher'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('reader', 'Reader')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('declined_for', models.CharField(blank=True, choices=[('incomplete', 'Incomplete Information'), ('duplicate', 'Duplicate Account'), ('spam', 'Suspected Spam/Fraud'), ('other', 'Other (see notes)')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news2u.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=200)),
                ('editor_interests', models.CharField(blank=True, max_length=200, null=True)),
                ('editor_bio', models.TextField()),
                ('editor_photo', models.ImageField(blank=True, null=True, upload_to='editor_photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalist_name', models.CharField(max_length=200)),
                ('journalist_bio', models.TextField()),
                ('journalist_photo', models.ImageField(blank=True, null=True, upload_to='journalist_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(blank=True, related_name='journalists', to='news2u.editor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_journalist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to='news2u.journalist'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('article_photo', models.ImageField(blank=True, null=True, upload_to='article_photos/')),
                ('editor_comments', models.TextField(blank=True, help_text='Editor feedback', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('ready_to_publish', 'Approved for Publication'), ('in_review_publisher', 'Under Publisher Review'), ('published_independent', 'Published Independently'), ('published_publisher', 'Published by Publisher'), ('revise', 'Revise')], default='draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_by_editor', to='news2u.editor')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_by_journalist', to='news2u.journalist')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_description', models.TextField()),
                ('publisher_logo', models.ImageField(blank=True, null=True, upload_to='publisher_logo/')),
                ('journalists', models.ManyToManyField(blank=True, related_name='publishers', to='news2u.journalist')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_title', models.CharField(max_length=255)),
                ('newsletter_content', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_editor', 'Awaiting Editor Review'), ('in_review', 'Being Edited'), ('in_review_publisher', 'Under Publisher Review'), ('ready_to_publish', 'Approved for Publication'), ('published_newsletter', 'Published by Journalist'), ('published_newsletter_by_publisher', 'Published by Publisher')], default='draft', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(blank=True, help_text='Articles included in this newsletter', related_name='articles_in_newsletters', to='news2u.article')),
                ('editor', models.ForeignKey(blank=True, help_text='Newsletter edited by ...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_newsletters', to='news2u.editor')),
                ('journalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalist_newsletters', to='news2u.journalist')),
                ('publisher', models.ForeignKey(blank=True, help_text='Publisher if newsletter is from a publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='news2u.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='editor',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='editors', to='news2u.publisher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to='news2u.publisher'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_by_publisher', to='news2u.publisher'),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reader_interests', models.TextField(blank=True, null=True)),
                ('reader_photo', models.ImageField(blank=True, null=True, upload_to='reader_photos/')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expiry_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
